package com.swp.commons.user.mapper;

import com.swp.commons.user.model.UserRoleRel;
import com.swp.commons.user.model.UserRoleRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_REL
     *
     * @mbg.generated Thu Sep 06 17:51:33 CST 2018
     */
    long countByExample(UserRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_REL
     *
     * @mbg.generated Thu Sep 06 17:51:33 CST 2018
     */
    int deleteByExample(UserRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_REL
     *
     * @mbg.generated Thu Sep 06 17:51:33 CST 2018
     */
    int deleteByPrimaryKey(String relId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_REL
     *
     * @mbg.generated Thu Sep 06 17:51:33 CST 2018
     */
    int insert(UserRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_REL
     *
     * @mbg.generated Thu Sep 06 17:51:33 CST 2018
     */
    int insertSelective(UserRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_REL
     *
     * @mbg.generated Thu Sep 06 17:51:33 CST 2018
     */
    List<UserRoleRel> selectByExample(UserRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_REL
     *
     * @mbg.generated Thu Sep 06 17:51:33 CST 2018
     */
    UserRoleRel selectByPrimaryKey(String relId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_REL
     *
     * @mbg.generated Thu Sep 06 17:51:33 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserRoleRel record, @Param("example") UserRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_REL
     *
     * @mbg.generated Thu Sep 06 17:51:33 CST 2018
     */
    int updateByExample(@Param("record") UserRoleRel record, @Param("example") UserRoleRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_REL
     *
     * @mbg.generated Thu Sep 06 17:51:33 CST 2018
     */
    int updateByPrimaryKeySelective(UserRoleRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ROLE_REL
     *
     * @mbg.generated Thu Sep 06 17:51:33 CST 2018
     */
    int updateByPrimaryKey(UserRoleRel record);
}